In [16]:
import numpy as np

in_arr = np.array([
                  [0, 0, 0, 0, 0],
                  [0, 1, 1, 0, 0],
                  [0, 1, 1, 0, 0],
                  [0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0]  
                ])
# create a kernel
kernel = np.ones((3, 3), dtype=np.int8)
kernel[1, 1] = 0
print(kernel)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [13]:
# define funtion
def fx(in_arr):
    out_arr = np.zeros_like(in_arr)     # create matrix outputs
    for i in range(1, in_arr.shape[0]-1):
        for j in range(1, in_arr.shape[1]-1):
            out_arr[i, j] = in_arr[i, j]    # assign outputs[i, j]
            temp = in_arr[i-1:i+2, j-1:j+2] # slice a matrix with shape (3, 3)
            sum = np.sum(np.multiply(kernel, temp))     # calculate sum of matrix
            if temp[1, 1]==1 and (sum<2 or sum>3):
                out_arr[i, j] = 0
            if temp[1, 1]==0 and sum==3:
                out_arr[i, j] = 1
    return out_arr          


In [17]:
for i in range(10):
    print(f'Result {i+1}' + '-----------')
    in_arr = fx(in_arr)
    print(in_arr)

Result 1-----------
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
Result 2-----------
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
Result 3-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result 4-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result 5-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result 6-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result 7-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result 8-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result 9-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result 10-----------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
